name: spots_xplorer_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  remixicon: ^1.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.3.0
  shared_preferences: ^2.3.3
  toastification: ^2.3.0
  easy_debounce: ^2.0.3
  select_field: ^2.0.0
  dropdown_textfield: ^1.2.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  choice: ^2.3.2
  flutter_screenutil: ^5.9.3
  simple_ripple_animation: ^0.1.0
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  change_app_package_name: ^1.5.0
  firebase_auth: ^5.5.2
  flutter_facebook_auth: ^6.0.4
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.27
  table_calendar: ^3.1.3
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  logger: ^2.6.0
  dartz: ^0.10.1
  isar: ^3.1.0+1
  hooks_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  flutter_local_notifications: ^19.4.0
  firebase_dynamic_links: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
